version: '3'
services:
  link:
      build:
        context: .
      restart: always
      ports:
          - 80:80
          - 443:443
          - 8765:8765
      volumes:
          - ./apps:/lantern/server/apps
          - ./web/public/platform:/lantern/server/web/public/platform
      environment:
          - CLOUD=false
          - DB=db/dev
          - SSL_PRIVATE_KEY=/lantern/server/certs/dev.lantern.link-key.pem
          - SSL_CERTIFICATE=/lantern/server/certs/dev.lantern.link.pem

volumes:
  apps:
