#!/bin/bash
# default commands may be replaced or extended

function reply() {
    echo $1|tr -d '\n'
}

if [ $1 == 'apps-update' ]; then
    cd $PWD/apps && git pull
    reply 'app update complete'
elif [ $1 == 'platform-update' ]; then
    cd $PWD && git pull 
    npm run pack
    reply 'platform update complete'
elif [ $1 == 'test' ]; then
    reply $PWD
fi